version: '3'

services:

  nginx:
    image: nginx
    container_name: nginx
    labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/router/conf.d:/etc/nginx/conf.d
      - ./data/router/vhost.d:/etc/nginx/vhost.d
      - ./data/router/html:/usr/share/nginx/html
      - ./data/router/certs:/etc/nginx/certs:ro

  nginx-gen:
    image: jwilder/docker-gen
    container_name: nginx-gen
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    restart: always
    volumes:
      - ./data/router/conf.d:/etc/nginx/conf.d
      - ./data/router/vhost.d:/etc/nginx/vhost.d
      - ./data/router/html:/usr/share/nginx/html
      - ./data/router/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: always
    volumes:
      - ./data/router/conf.d:/etc/nginx/conf.d
      - ./data/router/vhost.d:/etc/nginx/vhost.d
      - ./data/router/html:/usr/share/nginx/html
      - ./data/router/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: "nginx-gen"
      NGINX_PROXY_CONTAINER: "nginx"
